server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: task-service
          url: lb://task-service
          predicates:
            - Path=/tasks/**
        - id: student-service
          url: lb://student-service
          predicates:
            - Path=/students/**
        - id: teacher-service
          url: lb://teacher-service
          predicates:
            - Path=/teachers/**